server:
  listenAddress: "localhost"
  port: 3000
  debug: true
dbSync:
  host: "127.0.0.1"
  port: 54321
  user: "csyncdb"
  database: "csyncdb"
  maxConnections: 10
network: "mainnet"
tokenRegistryUrl: "https://tokens.cardano.org"
mithril:
  enabled: true
  aggregator: "https://aggregator.release-mainnet.api.mithril.network/aggregator"
