server:
  listenAddress: "localhost"
  port: 3000
  debug: true
dbSync:
  host: "http://127.0.0.1"
  port: 5432
  user: "you can type anything here, postgres is mocked"
  database: "you can type anything here, postgres is mocked"
  maxConnections: 0
  ssl: true
network: "mainnet"
tokenRegistryUrl: "http://localhost:3100"
mithril:
  enabled: true
  aggregator: "https://aggregator.release-mainnet.api.mithril.network/aggregator"
  snapshotMirrors:
    - originalUrl: "https://storage.googleapis.com/cdn.aggregator.pre-release-preview.api.mithril.network"
      mirrorUrl: "https://dummy-mithril-snapshot-cdn.com"
