name: Publish to Registry
on:
  - release
  - push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
      - name: Nix build docker image
        run: |
          nix build .#dockerImage
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push docker image to DockerHub
        run: |
          docker load < result
          set -ex
          echo "fmt"
          docker images
          echo "b"
          docker images | grep backend-ryo
          echo "q"
          docker images -q
          IMG_ID="$( docker images -q )"
          echo "IMG_ID $IMG_ID"
          docker tag $IMG_ID backend-ryo:latest
          docker tag $IMG_ID backend-ryo:${{ github.event.release.tag_name }}
          docker push srksrk/backend-ryo:latest
          docker push srksrk/backend-ryo:${{ github.event.release.tag_name }}
